"""Injected gravitational-wave signals for the gap-imputation training set.

Two injection classes are supported:

1. **SMBHB chirp** — a post-Newtonian inspiral waveform generated by the upstream
   :mod:`smbhb_inspiral` package. The upstream integrator returns a trajectory on
   an internal log-spaced time grid; here we resample onto a user-supplied
   uniform cadence and place the merger at a chosen offset within the segment.

2. **Monochromatic galactic binary** — a single sinusoid at a fixed frequency
   with a small linear frequency drift, standing in for the many near-monochromatic
   detached white-dwarf binaries that dominate the LISA-band foreground.

In both cases the signal is returned on the same uniform time grid the noise
module uses, so the two can be added pointwise to form the clean "truth" strain
fed into the dataset.

**Important scope reminder**

This is not a realistic LISA injection catalogue. The SMBHB population is drawn
uniformly in ``(log M_tot, log q, log d_L, cos iota)`` from ranges that make the
chirp visible inside a short segment, not from the astrophysical mass function.
The monochromatic population is one sinusoid per segment, not the ~30 million
resolved and unresolved sources LISA will actually see.

References
----------
Maggiore, M. 2007, *Gravitational Waves: Theory and Experiments*, Oxford.
Peters, P. C. 1964, Phys. Rev. 136, B1224.
Blanchet, L. 2014, Living Rev. Relativity 17, 2.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

import numpy as np
import numpy.typing as npt
from smbhb_inspiral.physics import f_isco, integrate_inspiral
from smbhb_inspiral.waveform import strain_plus

__all__ = [
    "InjectionMeta",
    "SignalSegment",
    "inject_smbhb_chirp",
    "inject_monochromatic",
    "draw_smbhb_params",
    "draw_monochromatic_params",
]


SignalType = Literal["smbhb", "monochromatic", "quiet"]


@dataclass(frozen=True)
class InjectionMeta:
    """Metadata describing the injection drawn for a training segment.

    Kept next to the waveform so the evaluation stage can stratify reconstruction
    quality and matched-filter SNR recovery by the injection parameters.

    Attributes
    ----------
    kind : SignalType
        Which injection type was used. ``"quiet"`` indicates noise only.
    params : dict[str, float]
        The physical parameter draw, keyed by parameter name. Empty for
        ``kind == "quiet"``.
    """

    kind: SignalType
    params: dict[str, float]


@dataclass(frozen=True)
class SignalSegment:
    """A clean (noise-free) signal strain on a uniform time grid."""

    strain: npt.NDArray[np.float64]
    fs_hz: float
    meta: InjectionMeta

    @property
    def n_samples(self) -> int:
        return int(self.strain.size)


# ---------------------------------------------------------------------------
# Parameter draws
# ---------------------------------------------------------------------------


def draw_smbhb_params(
    rng: np.random.Generator,
    m_total_range_msun: tuple[float, float] = (1.0e5, 1.0e7),
    q_range: tuple[float, float] = (0.1, 1.0),
    d_l_range_mpc: tuple[float, float] = (5.0e2, 1.0e4),
    iota_range_rad: tuple[float, float] = (0.0, np.pi),
) -> dict[str, float]:
    """Draw SMBHB parameters for a single injection.

    Samples are uniform in ``log10(M_tot)``, ``log10(q)``, ``log10(d_L)``, and
    ``cos(iota)`` over the requested ranges. These priors are deliberately
    coarse; they populate the mass / distance / orientation plane well enough
    to probe how reconstruction quality depends on chirp duration and amplitude.
    """
    log_m_lo, log_m_hi = np.log10(m_total_range_msun)
    m_total: float = 10.0 ** rng.uniform(log_m_lo, log_m_hi)

    log_q_lo, log_q_hi = np.log10(q_range)
    q: float = 10.0 ** rng.uniform(log_q_lo, log_q_hi)

    log_d_lo, log_d_hi = np.log10(d_l_range_mpc)
    d_l_mpc: float = 10.0 ** rng.uniform(log_d_lo, log_d_hi)

    cos_iota_lo: float = float(np.cos(iota_range_rad[1]))
    cos_iota_hi: float = float(np.cos(iota_range_rad[0]))
    cos_iota: float = rng.uniform(
        min(cos_iota_lo, cos_iota_hi), max(cos_iota_lo, cos_iota_hi)
    )
    iota: float = float(np.arccos(np.clip(cos_iota, -1.0, 1.0)))

    # Derived component masses from M_tot and q (q = m2/m1 ≤ 1).
    m1: float = m_total / (1.0 + q)
    m2: float = m_total - m1

    return {
        "m1_msun": m1,
        "m2_msun": m2,
        "m_total_msun": m_total,
        "q": q,
        "d_l_mpc": d_l_mpc,
        "iota_rad": iota,
    }


def draw_monochromatic_params(
    rng: np.random.Generator,
    f_range_hz: tuple[float, float] = (3.0e-4, 1.0e-2),
    amp_range: tuple[float, float] = (5.0e-22, 5.0e-20),
    fdot_range_hz_per_s: tuple[float, float] = (0.0, 1.0e-16),
) -> dict[str, float]:
    """Draw parameters for a single near-monochromatic galactic-binary source.

    The ranges above are loose stand-ins tuned to put the sinusoid in the
    LISA-sensitive mHz band and at amplitudes comparable to the Robson+19 PSD
    at those frequencies. They are not drawn from the LISA Verification Binary
    catalogue.
    """
    log_f_lo, log_f_hi = np.log10(f_range_hz)
    f_hz: float = 10.0 ** rng.uniform(log_f_lo, log_f_hi)

    log_a_lo, log_a_hi = np.log10(amp_range)
    amplitude: float = 10.0 ** rng.uniform(log_a_lo, log_a_hi)

    fdot: float = float(rng.uniform(*fdot_range_hz_per_s))

    phase: float = float(rng.uniform(0.0, 2.0 * np.pi))

    return {
        "f_hz": f_hz,
        "amplitude": amplitude,
        "fdot_hz_per_s": fdot,
        "phase_rad": phase,
    }


# ---------------------------------------------------------------------------
# SMBHB chirp injection
# ---------------------------------------------------------------------------


def _pick_start_frequency(
    m_total_msun: float,
    segment_duration_s: float,
    target_fraction_in_band: float = 0.6,
) -> float:
    """Choose an initial GW frequency so the inspiral lasts long enough to fill
    a useful fraction of the segment before merger.

    The Peters (1964) 0PN merger time ``t_merge ~ (5/256) c^5 a_0^4 / (G^3 m1 m2 M)``
    is monotonic in ``f_0``, so we use a crude geometric guess: pick ``f_0`` such
    that the analytic ISCO frequency is ``1/target_fraction_in_band`` factors of
    10 above it, capped to the LISA band. A fixed-point refinement would be
    prettier but unnecessary here — the downstream resampler will trim whatever
    length we end up with.
    """
    f_isco_hz: float = f_isco(m_total_msun)
    # Heuristic: start a few e-folds below ISCO so the chirp sweeps across the
    # segment rather than sitting in one bin.
    # Concrete recipe — for M_tot = 1e6 Msun, f_isco ~ 4 mHz; starting at
    # ~1e-2 * f_isco sweeps ~2 orders of magnitude, visible in a 10-hour segment.
    f0: float = 1.0e-2 * f_isco_hz
    # Clamp to the LISA analytic-PSD range.
    return float(np.clip(f0, 1.0e-5, 0.5 * f_isco_hz))


def inject_smbhb_chirp(
    n_samples: int,
    fs_hz: float,
    rng: np.random.Generator,
    params: dict[str, float] | None = None,
    merger_position: float | None = None,
) -> SignalSegment:
    """Generate a plus-polarization SMBHB chirp on a uniform time grid.

    Parameters
    ----------
    n_samples : int
        Length of the output segment in samples.
    fs_hz : float
        Sampling frequency in Hz.
    rng : np.random.Generator
        Random generator used when ``params`` is ``None`` (to draw parameters)
        and when ``merger_position`` is ``None`` (to draw the merger offset).
    params : dict[str, float] or None, optional
        Output of :func:`draw_smbhb_params`. If ``None``, a fresh draw is made
        with the default prior ranges.
    merger_position : float or None, optional
        Fractional position of the merger inside the segment, in ``[0, 1]``.
        ``0.5`` centres the merger; ``1.0`` places it at the last sample. If
        ``None``, drawn uniformly in ``[0.3, 0.9]`` so the chirp is always
        at least partially visible.

    Returns
    -------
    SignalSegment
        The plus-polarization strain ``h_+(t)`` resampled onto the uniform
        grid, with zeros everywhere outside the integrated trajectory.

    Notes
    -----
    Only the plus polarization is used — the cross polarization is coherent
    but carries no additional information about the gap-imputation problem
    at the phenomenological level we are operating on here. If the ablation
    later shows this matters we will revisit.

    The upstream ``integrate_inspiral`` is deterministic in its own right; the
    ``rng`` argument only enters through the parameter draw and merger-offset
    draw. Passing a pre-built ``params`` dictionary together with a fixed
    ``merger_position`` gives fully reproducible output.
    """
    p: dict[str, float] = params if params is not None else draw_smbhb_params(rng)
    meta = InjectionMeta(kind="smbhb", params=dict(p))

    segment_duration_s: float = n_samples / fs_hz
    f0_hz: float = _pick_start_frequency(p["m_total_msun"], segment_duration_s)

    trajectory = integrate_inspiral(
        m1=p["m1_msun"],
        m2=p["m2_msun"],
        f0=f0_hz,
        pn_order=1,
    )

    h_plus_traj: npt.NDArray[np.float64] = strain_plus(
        trajectory=trajectory,
        d_l_mpc=p["d_l_mpc"],
        iota=p["iota_rad"],
    )

    # Uniform output time grid (seconds).
    t_out: npt.NDArray[np.float64] = np.arange(n_samples, dtype=np.float64) / fs_hz

    # Place the trajectory so its endpoint (merger) falls at the chosen
    # fractional position within the output segment.
    if merger_position is None:
        merger_position = float(rng.uniform(0.3, 0.9))
    merger_position = float(np.clip(merger_position, 0.0, 1.0))
    t_merger_out: float = merger_position * segment_duration_s

    # Shift trajectory so t_traj_end maps to t_merger_out.
    t_traj_end: float = float(trajectory.t[-1])
    t_traj_shifted: npt.NDArray[np.float64] = (
        trajectory.t - t_traj_end + t_merger_out
    )

    # Resample via linear interpolation. Points outside the trajectory return 0.
    h_plus_out: npt.NDArray[np.float64] = np.interp(
        t_out,
        t_traj_shifted,
        h_plus_traj,
        left=0.0,
        right=0.0,
    )

    return SignalSegment(strain=h_plus_out, fs_hz=float(fs_hz), meta=meta)


# ---------------------------------------------------------------------------
# Monochromatic galactic-binary injection
# ---------------------------------------------------------------------------


def inject_monochromatic(
    n_samples: int,
    fs_hz: float,
    rng: np.random.Generator,
    params: dict[str, float] | None = None,
) -> SignalSegment:
    """Generate a near-monochromatic sinusoid with small frequency drift.

    Parameters
    ----------
    n_samples : int
        Segment length in samples.
    fs_hz : float
        Sampling frequency in Hz.
    rng : np.random.Generator
        Used only when ``params`` is ``None``.
    params : dict[str, float] or None, optional
        Output of :func:`draw_monochromatic_params`. Defaults to a fresh draw.

    Returns
    -------
    SignalSegment
        Strain ``A cos(2 pi (f t + 0.5 fdot t^2) + phi)``.
    """
    p: dict[str, float] = (
        params if params is not None else draw_monochromatic_params(rng)
    )
    meta = InjectionMeta(kind="monochromatic", params=dict(p))

    t: npt.NDArray[np.float64] = np.arange(n_samples, dtype=np.float64) / fs_hz
    phase: npt.NDArray[np.float64] = (
        2.0 * np.pi * (p["f_hz"] * t + 0.5 * p["fdot_hz_per_s"] * t**2)
        + p["phase_rad"]
    )
    strain: npt.NDArray[np.float64] = p["amplitude"] * np.cos(phase)

    return SignalSegment(strain=strain, fs_hz=float(fs_hz), meta=meta)
